### PR TITLE
Publish from Jekyll

### PR DESCRIPTION
**Pull request by sarayourfriend**
Depends on #16

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Was this supposed to be a PR against #16? It looks like they include common commits

**Comment by sarayourfriend** [comment]
Oops yes I need to rebase it after #16 gets merged I guess. To get Netlify to branch deploy it it had to target main is why I did that.

**Comment by sarayourfriend** [comment]
@AetherUnbound Fixed!

**Review by AetherUnbound — APPROVED** [review]
🎉

**Pull request merged**
