### PR TITLE
Add Netlify callout

### PR DESCRIPTION
**Pull request by sarayourfriend**

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]

**Comment by AetherUnbound** [comment]
I know on other sites we have the `noreferrer` tags set up for href links, did we want to do that here?

**Comment by sarayourfriend** [comment]
> I know on other sites we have the noreferrer tags set up for href links, did we want to do that here?

Hmmmm I'm not sure. I thought about it at first but thought that maybe because it's a resource meant to link people to stuff that we didn't need it. What do you think? On other pages I think because it's a sensitive resource we might want them.

**Comment by AetherUnbound** [comment]
> Hmmmm I'm not sure. I thought about it at first but thought that maybe because it's a resource meant to link people to stuff that we didn't need it. What do you think? On other pages I think because it's a sensitive resource we might want them.

I personally hadn't seen that before SeattleDSA/OpenOversight#13 so I wasn't sure how important it was :sweat_smile: If it's no big deal then we can forget it!

**Comment by sarayourfriend** [comment]
> I personally hadn't seen that before SeattleDSA/OpenOversight#13 so I wasn't sure how important it was 😅 If it's no big deal then we can forget it!

I think it's only important when linking _from_ a sensitive resource, i.e., if we don't want the location we're linking to to know where the person came from. For example we don't need it in the directory because we control all of the resources (except a few, which we should probably update to include the `rel` attribute).

**Pull request merged**
