### PR TITLE
Dark theme QOL improvements

### PR DESCRIPTION
**Pull request by AetherUnbound**
This PR includes some QOL improvements that came about from #34. It seems that there was some initial work on this front that wasn't quite finished so I mostly just pushed things across the finish line.

Changes:
* Rather than a static theme icon, the icons now switch between light (moon) and dark (sun) where appropriate
* The background color of the theme button contrasts with the theme itself to better showcase its functionality
* All color changes now transition, as opposed to just the theme button's colors
* The hover color of the theme button is now gray, which serves better than the light blue it was previously

Example (gif quality is low so the transition isn't as apparent):
Peek 2021-09-01 14-46

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Something I'm noticing, because we're no longer basing the CSS on the media query, it flashes to dark mode first then switches to light mode if you start on light mode. To reproduce this, start in light mode and load the site... and you should see it flash dark to light.

Otherwise this looks great 🙂

**Comment by AetherUnbound** [comment]
> Something I'm noticing, because we're no longer basing the CSS on the media query, it flashes to dark mode first then switches to light mode if you start on light mode. To reproduce this, start in light mode and load the site... and you should see it flash dark to light.

How should we mitigate this?

**Review by vertexactual — APPROVED** [review]
Looks solid and stable. Good to merge.

**Comment by vertexactual** [comment]
> > Something I'm noticing, because we're no longer basing the CSS on the media query, it flashes to dark mode first then switches to light mode if you start on light mode. To reproduce this, start in light mode and load the site... and you should see it flash dark to light.
> 
> How should we mitigate this?

[There doesn't seem to be an easy solution.](https://css-tricks.com/flash-of-inaccurate-color-theme-fart/)
Could delay rendering until the `localStorage` check is complete. Could also set a cookie and use that instead of `localStorage` since it could happen slightly earlier, but that likely wouldn't _fix_ it, it'd just cut the frames of the light theme.

To be super practical, I would just default to dark theme. That way the worst is user gets a flash of dark content that brightens, rather than the opposite.

**Comment by AetherUnbound** [comment]
That's all super helpful @vertexactual, thanks! I think with that in mind, we'll probably stick with what we have now. The dark theme is available for folks who want it, but the theme won't change for people who have used the site before and haven't set any system preferences.

**Pull request merged**
